<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

genesis_structural_wrap( 'site-inner', 'close' );
echo '</div>'; //* end .site-inner or #inner

do_action( 'genesis_before_footer' );
$image = get_field('footer_logo', 'option');
?>
<footer class="footer-custom">
    <div class="footer-container">
        <div class="footer-logo left">
            <img width="200px" src="<?php echo $image['url']; ?>" alt="AirTaxi.PH"/>
            <small>© Copyright 2017. All Rights Reserved. Web Design and Development by <a href="http://7thmedia.com/" title="7th Media Digital Studio Inc." target="_blank">7th Media</a>
            </small>
        </div>

        <div class="footer-links right">
            <a href="https://www.facebook.com/AirTaxiPH" class="footer-link facebook"><i class="fa fa-facebook-official fa-2x"></i></a>
            <a href="https://www.instagram.com/airtaxi.ph/" class="footer-link instagram"><i class="fa fa-instagram fa-2x"></i></a>
        </div>
    </div>
</footer>
<?php
do_action( 'genesis_after_footer' );

echo '</div>'; //* end .site-container or #wrap

do_action( 'genesis_after' );
wp_footer(); //* we need this for plugins
?>
</body>
</html>
               

               