<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

genesis_structural_wrap( 'site-inner', 'close' );
echo '</div>'; //* end .site-inner or #inner

do_action( 'genesis_before_footer' );
?>
<footer class="footer-custom">
    <div class="footer-container">
        <div class="footer-logo left">
            <img width="200px" src="http://localhost/Projects/airtaxi/wp-content/uploads/2016/09/AIRTAXI.png" alt="AirTaxi.PH"/>
            <small>© Copyright 2016. All Rights Reserved. Designed and Developed by 7th Media</small>
        </div>

        <div class="footer-links right">
            <a href="https://www.facebook.com/AirTaxiPH" class="footer-link facebook"><i class="fa fa-facebook-official fa-2x"></i></a>
            <a href="https://www.instagram.com/airtaxi.ph/" class="footer-link instagram"><i class="fa fa-instagram fa-2x"></i></a>
        </div>
    </div>
</footer>
<?php
do_action( 'genesis_after_footer' );

echo '</div>'; //* end .site-container or #wrap

do_action( 'genesis_after' );
wp_footer(); //* we need this for plugins
?>
</body>
</html>
               

               